# Generated by Django 3.0.6 on 2020-07-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_name', models.CharField(max_length=100)),
                ('des_location', models.CharField(max_length=100)),
                ('des_duration', models.IntegerField()),
                ('des_price', models.IntegerField()),
                ('des_description', models.CharField(max_length=500)),
                ('des_image', models.ImageField(upload_to='Destination_images/')),
            ],
            options={
                'db_table': 'Destination',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_location', models.CharField(max_length=100)),
                ('hotel_duration', models.IntegerField()),
                ('hotel_price', models.IntegerField()),
                ('hotel_description', models.CharField(max_length=500)),
                ('hotel_image', models.ImageField(upload_to='Hotel_images/')),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('tour_location', models.CharField(max_length=100)),
                ('tour_duration', models.IntegerField()),
                ('tour_price', models.IntegerField()),
                ('tour_description', models.CharField(max_length=500)),
                ('tour_image', models.ImageField(upload_to='Tour_images/')),
                ('tour_des_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Admin.Destination')),
                ('tour_hotel_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Admin.Hotel')),
            ],
            options={
                'db_table': 'Tour',
            },
        ),
    ]
