# Generated by Django 3.0.6 on 2020-07-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_contact', models.CharField(max_length=10)),
                ('contact_message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=100)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'User_login',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=100)),
                ('booking_email', models.EmailField(max_length=100)),
                ('booking_contact', models.CharField(max_length=15)),
                ('booking_date', models.CharField(max_length=200)),
                ('booking_adults', models.CharField(max_length=5)),
                ('booking_kids', models.CharField(max_length=5)),
                ('booking_message', models.CharField(max_length=500)),
                ('booking_tour_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Admin.Tour')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
